name: Check Localization File Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find all localization .txt files
        working-directory: game
        run: |
          # Find all .txt files in the localization folder and its subdirectories
          find ./resource/localization -name "*.txt"

      - name: Check localization format
        working-directory: game
        run: |
          # Check each .txt file found in the localization folder
          find ./resource/localization -name "*.txt" | while read file; do
            echo "Checking format of $file"
            if ! grep -qP "^\s*(//.*|\"[a-zA-Z0-9_]+\"\s*\"[^\"]+\")\s*$" "$file"; then
              echo "$file is incorrectly formatted. Make sure every line follows \"key\" \"value\" pattern or is a comment starting with //."
              exit 1
            fi
          done

      - name: Format check passed
        run: echo "All localization files are correctly formatted!"
