name: Check Localization File Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check localization format
        run: |
          # Ensure localization.txt exists and isn't malformed
          if ! grep -qP "^\s*(//.*|\"[a-zA-Z0-9_]+\"\s*\"[^\"]+\")\s*$" localization.txt; then
            echo "Localization file is incorrectly formatted. Make sure every line follows \"key\" \"value\" pattern or is a comment starting with //."
            exit 1
          fi

      - name: Format check passed
        run: echo "Localization file format is correct!"
